from collections.abc import AsyncIterator
from contextlib import asynccontextmanager

from fastapi import FastAPI

from app.mcp_server import mcp_http_app, mcp_server
from app.routers.analysis_router import router as analysis_router
from app.routers.portfolio_router import router as portfolio_router


@asynccontextmanager
async def lifespan(_: FastAPI) -> AsyncIterator[None]:
    """Run the MCP transport session manager with the FastAPI application."""
    async with mcp_server.session_manager.run():
        yield


app = FastAPI(
    title="agentic-stock-analysis API",
    description=(
        "Read reports generated by agentic-stock-analysis and manage the "
        "CSV-backed portfolio."
    ),
    version="1.0.0",
    lifespan=lifespan,
)

app.include_router(analysis_router)
app.include_router(portfolio_router)
app.mount("/mcp", mcp_http_app, name="mcp")
