from fastapi import FastAPI

from app.routers.analysis_router import router as analysis_router
from app.routers.entry_strategy_router import router as entry_strategy_router
from app.routers.hold_strategy_router import router as hold_strategy_router

app = FastAPI(
    title="agentic-stock-analysis API",
    description="Read reports generated by agentic-stock-analysis.",
    version="1.0.0",
)

app.include_router(analysis_router)
app.include_router(entry_strategy_router)
app.include_router(hold_strategy_router)
