from fastapi import FastAPI

from app.routers.analysis_router import router as analysis_router

app = FastAPI(
    title="agentic-stock-analysis API",
    description="Read reports generated by agentic-stock-analysis.",
    version="1.0.0",
)

app.include_router(analysis_router)
